### ISSUE TITLE
Performance issues on Ember 1.13.0

### ISSUE THREAD

**Issue by neojp** [pzuraq/ember-inputmask#10]
I've run into performance issues with `credit card` & `phone number` components under Ember 1.13.0; they are simply to slow to even be usable. All other ember-inputmask components work fine.

``` handlebars
{{credit-card-input unmaskedValue=foo1 cardType=bar1 separator=" "}}
{{phone-number-input unmaskedValue=foo2 extensions=false}}
```

Thinking out loud, there might be an architectural problem on how data gets passed around, an observer going rogue or some sort of memory leak. I'm going to take a look at it. In the meantime I'm leaving this issue to keep track of things.

**Comment by Mithrilhall** [comment]
I'm experiencing the performance issue as well with the ```{{phone-number-input}}```

**Comment by nicnash** [comment]
I'm having performance issues also with phone-number-input and on ie 11 it moves focus to the end making it unusable

**Comment by pzuraq** [comment]
Hey, sorry it's taken me so long to get back to this.

To be honest I've dropped this addon from our stack specifically because of issues like this. Even on it's own, jquery.inputmask is a _very_ large plugin and it's pretty slow. 

If anyone wants to take a stab at improving that perf, by all means. In the meantime, I'm going to be looking for a more general and high performance masking library that we can build a better set of masking tools in general on top of. I'll continue to merge PRs, and if anyone wants to take over this project I'll gladly transfer ownership, but I'm not going to be actively developing it any longer.

**Comment by BillBrower** [comment]
@pzuraq is there another addon that you're using in place of this one?

**Comment by pzuraq** [comment]
I haven't actually had the need to use input masking in an app for some time, but if I needed it again I'd probably go with a thin wrapper around [@estelle's excellent input masking library](https://github.com/estelle/input-masking) library. The approach is much more minimal, essentially pure javascript which makes it very small and much more performant.

**Comment by BillBrower** [comment]
Thanks @pzuraq! That does look really nice. By thin wrapper do you mean something like a component that wraps ember's input helper in it's template and instantiates input masking's `InputMask` object in it's js via the `didInsertElement()` method?

**Comment by pzuraq** [comment]
Yep, exactly. This way the component can focus on the UI part and InputMask can focus on the masking logic independently
