### ISSUE TITLE
No tag found that was able to satisfy 3.2.7. Jquery.inputmask moved

### ISSUE THREAD

**Issue by ashikodes** [pzuraq/ember-inputmask#34]
ember-inputmask still tries to install jquery.inputmast from the repo https://github.com/RobinHerbots/jquery.inputmask.git#3.2.7. 
I realized this has been moved to https://github.com/RobinHerbots/Inputmask

**Comment by leizhao4** [comment]
@ashikodes Which version of ember-inputmask are you using?

**Comment by ashikodes** [comment]
@leizhao4 ember-inputmask@0.2.3

**Comment by leizhao4** [comment]
@ashikodes Ah I see. 0.2.x hasn't been updated for the new Inputmask package. Would you mind create a pull request?

Alternatively, you could use 0.4.0-beta.2 which is already updated.

**Comment by garrypolley** [comment]
I added this issue: https://github.com/RobinHerbots/jquery.inputmask/issues/2

**Comment by leizhao4** [comment]
@ashikodes @garrypolley I updated the Bower package name to `Inputmask` and released 0.2.4. Please try if this fixes the problem.

**Comment by leizhao4** [comment]
I also encourage everyone to try the new v0.4.0-beta.2 which I think is fairly stable now. The v0.4.x branch does not depend on jQuery, pulls the package from NPM instead of Bower, and is more actively maintained. I personally don't use 0.2.x versions and don't have much time maintaining them.

I haven't released the final version of v0.4.0 because Inputmask is making lots of breaking changes recently. I want to wait until the API and file structure become more stable.

**Comment by joestein216** [comment]
Thanks @leizhao4 for the quick release.  I was trying to cherry-pick some commits and put together a pull request, but Inputmask library changed so fast there was no in-between 'rename/repoint' commit.  I think your v0.2.4 release is valuable for showing that change, but also agree that Inputmask latest and your latest are the way to go.  Very cool Inputmask no longer requires jquery and this addon no longer will need to update our bower.json.  I will be holding at v.0.2.4 until we upgrade our Ember 2.4 app to Ember 2.12 LTS very soon.  Thanks again!

**Comment by leizhao4** [comment]
I'm assuming this issue is fixed. Please let me know if it's not and I will reopen it.
